# ??? PAYMENT SERVICE ???
spring.application.name=payment-service
server.port=${SERVER_PORT:8084}

# Base de datos
spring.datasource.url=jdbc:postgresql://${PAYMENT_DB_HOST:localhost}:5432/${PAYMENT_DB_NAME:paymentdb}
spring.datasource.username=${PAYMENT_DB_USER:postgres}
spring.datasource.password=${PAYMENT_DB_PASSWORD:Jfrc11$$}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# JWT
jwt.secret=${JWT_SECRET:default_secret}

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:9092}
app.kafka.enabled=${KAFKA_ENABLED:false}

# MercadoPago
mercadopago.access-token=${MP_ACCESS_TOKEN:APP_USR-3663017278465000-060823-f6d52fd152cf486a95373feafaa004d6-3446057752}

mercadopago.public-key=${MP_PUBLIC_KEY:APP_USR-e773e7b8-bd35-4061-adbe-b5d74ae03703}
app.mp-sandbox=${MP_SANDBOX:true}
# Mercado Pago Producion
# app.mp-sandbox=false
# mercadopago.access-token=${MP_ACCESS_TOKEN_PROD}
# app.frontend-url=https://tudominio.com

# Frontend
app.frontend-url=${FRONTEND_URL:https://eventperu.francowe.me}

# SUNAT - Configuracion completa
sunat.ruc=${SUNAT_RUC:20000000001}
sunat.razon-social=${SUNAT_RAZON_SOCIAL:EMPRESA DE PRUEBA S.A.C.}
sunat.usuario-sol=${SUNAT_USER:MODDATOS}
sunat.clave-sol=${SUNAT_PASS:moddatos}
sunat.certificado-path=${SUNAT_CERT_PATH:classpath:certificado/sunat_prueba.pfx}
sunat.certificado-password=${SUNAT_CERT_PASS:sunat_prueba}
sunat.url-beta=${SUNAT_URL_BETA:https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService}
sunat.url-produccion=${SUNAT_URL_PROD:https://e-factura.sunat.gob.pe/ol-ti-itcpfegem/billService}
sunat.modo=${SUNAT_MODO:beta}

